### ISSUE TITLE
self.weight is not defined in file `models/layers.py` 15 lines

### ISSUE THREAD

**Issue by Fancy-hjyp** [ngaggion/HybridGNet#1]
Hello, gaggion

There was an error when i run `Example_3.ipynb`, prompting that `AttributeError: 'ChebConv_Coma' object has no attribute 'weight'`, I guess the reason is that attribute named `self.weight` is not defined in file `HybridGNet/models/layers.py` 15 lines. Do you know how to slove this problem, could you help me ?

Thank you very much~

**Comment by ngaggion** [comment]
Hello Tomoko, I'm guessing the problem is with your version of PyTorch Geometric. As on the layers.py file we redefine the ChebConv, you need to have the same version (1.7.0)

**Comment by Fancy-hjyp** [comment]
> Hello Tomoko, I'm guessing the problem is with your version of PyTorch Geometric. As on the layers.py file we redefine the ChebConv, you need to have the same version (1.7.0)

Yes，That‘s true. The code can run correctly when i change the version of PyTorch Geometric(1.7.0). Thank you very much~
