### ISSUE TITLE
How to generate pca npy ?

### ISSUE THREAD

**Issue by chouqin3** [ngaggion/HybridGNet#2]
The code does not include how to generate npy, e.g. models/pca64.npy. Could you give me more details. Thank you.

**Comment by ngaggion** [comment]
Hello, I have a script in other repo to do PCA using scikit learn. For doing the PCA, I take the vectorized landmark representation, do 100 epochs of data augmentation for the landmarks (the same as the one using for training the models) and then do PCA with scikit-learn.

https://github.com/ngaggion/Chest-x-ray-Baselines/blob/main/getPCA.ipynb

**Comment by chouqin3** [comment]
Got it. Thanks for your timely reply.😊👍
