### ISSUE TITLE
No module named 'models.hybridNoPool'

### ISSUE THREAD

**Issue by kitbransby** [ngaggion/HybridGNet#3]
When running ```python trainerHybrid.py --help```
I get the error 
```
Traceback (most recent call last):
File "[...]/HybridGNet/trainerHybrid.py", line 20, in <module>
    from models.hybridNoPool import Hybrid as HybridNoPool
ModuleNotFoundError: No module named 'models.hybridNoPool'
```
It seems like there is no hybridNoPool.py in your repo. Is this correct? the trainer runs without error if i comment out line 20

**Comment by ngaggion** [comment]
Hello, it seems there was a missing file. I've just uploaded it.
Please tell me if you find any other issues

**Comment by kitbransby** [comment]
Thanks :)

**Comment by kitbransby** [comment]
Ah I believe the weights for hybrid no pool are also not in your google drive folder. Id be grateful if you could upload 

```FileNotFoundError: [Errno 2] No such file or directory: '../weights/hybrid_no_pool/bestMSE_2000.pt'```

**Comment by ngaggion** [comment]
I've uploaded a zip with the file to the drive folder. Please place it on the weights folder.
