### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by NRahilhussain** [ngaggion/HybridGNet#4]
Please upload one of the file namely torch_geometric.
If there is any other module or file imported in this, kindly upload that too. 
Thanks. 
You can mail me as well at (rahilh854@gmail.com)

**Comment by ngaggion** [comment]
There is no "torch_geometric" file, that referes to the PyTorch Geometric library. Install the library using the environment .yml to get the correct version and it should work

**Comment by NRahilhussain** [comment]
Thank you sir I'll install that
