### ISSUE TITLE
Trained network for generating Landmarks from Dense Segmentation

### ISSUE THREAD

**Issue by aipatr** [ngaggion/HybridGNet#5]
Thank you very much for your repository. In the paper you clearly state that in order to obtain landmarks from dense segmentation you trained your HybridGnet with dense segmentations as input. Would it be possible to have this trained models? I am working on a project that would require converting dense segmentations to Landmarks.

Best regards.

**Comment by ngaggion** [comment]
Hello, in the [google drive folder](https://drive.google.com/drive/folders/1YcmT8JzdtNuaWVqhv8Zfm00lF47w0eU5) containing the model weights, there is a weights.zip file. You can find there the Seg2Graph folder containing the weights from dense segmentation masks to landmarks, for both heart and lungs segmentation masks as one input. The HybridGNet model weights with two skip connections is named "double_s2g", sorry for the lack of organization of this part. Here is the [evaluation code](https://github.com/ngaggion/HybridGNet/blob/main/Results/Evaluate_JSRT-S2G.ipynb), it may help to see how to load this models.

My recommendation is that you train a model to do this, as it does not requires images and the training process is quite fast. Here you have a [trainer script](https://github.com/ngaggion/HybridGNet/blob/main/trainerSeg2graph.py) to do this. You can choose if you want to generate masks from lungs only, or lungs and heart. The main idea is that you can do a lot of data augmentation to the landmark contours (scaling, rotation, shearings, etc) then simply fill them with opencv to get segmentation masks. Doing this augmentation to a set of points is ton of times faster than doing it to the images.

Email me if you need extra help
